SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMP;

SELECT * FROM EMP
WHERE UPPER(ENAME) LIKE UPPER('%smi%');

SELECT CONCAT(EMPNO, ENAME),
CONCAT(EMPNO, CONCAT(':', ENAME))
FROM EMP WHERE ENAME = 'SMITH';

SELECT EMPNO || ENAME,
EMPNO || ':' || ENAME
FROM EMP WHERE ENAME = 'SMITH';

SELECT ROUND(1.234)
FROM DUAL;

SELECT * FROM DUAL;

SELECT SYSDATE AS NOW,
SYSDATE - 1 AS YESTERDAY,
SYSDATE + 1 AS TOMORROW
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간
FROM DUAL;

SELECT * FROM EMP
WHERE HIREDATE = '1981/12/03';

-- 1981년 입사자들 출력
SELECT * FROM EMP
WHERE HIREDATE BETWEEN TO_DATE('1981-06-01', 'YYYY-MM-DD') AND TO_DATE('2023-07-31', 'YYYY-MM-DD');

SELECT * FROM EMP
WHERE HIREDATE > TO_DATE('1981-06-01', 'YYYY-MM-DD');

SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM,
	NVL(COMM, 0),
	SAL*12 + NVL(COMM, 0) AS ANNSAL
FROM EMP
ORDER BY ANNSAL;






