SELECT * FROM EMP;

-- 프로젝션(열) 조회
SELECT EMPNO, ENAME, DEPTNO
FROM emp; -- 테이블 명

SELECT DEPTNO
FROM emp;

SELECT DISTINCT DEPTNO -- 중복없이 출력
FROM emp;

SELECT DISTINCT JOB, DEPTNO -- 중복없이 출력
FROM emp;

SELECT ENAME, SAL, SAL*12+COMM, COMM
FROM emp; -- 테이블 명

SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM -- 수식의 열에 별칭 부여. 공백이 포함되면 ""로 둘러싸기.
FROM emp; -- 테이블 명

SELECT * FROM EMP
ORDER BY SAL; -- 오름차순 정렬

SELECT * FROM EMP
ORDER BY SAL DESC; -- 내림차순 정렬

SELECT * FROM EMP
ORDER BY DEPTNO ASC, SAL DESC; -- DEPTNO로 오름차순 정렬, 동률이면 SAL로 내림차순 정렬

SELECT * FROM EMP
ORDER BY HIREDATE DESC;

SELECT * FROM EMP
WHERE DEPTNO = 30; -- 셀렉션(행)

SELECT * FROM dept
WHERE DEPTNO = 30; -- 셀렉션(행)

SELECT * FROM EMP
WHERE DEPTNO = 30
	AND JOB = 'SALESMAN'; -- 작은 따옴표를 써야함

SELECT * FROM EMP
WHERE DEPTNO = 30
	OR JOB = 'CLERK'
ORDER BY DEPTNO, ENAME;

SELECT * FROM EMP
WHERE SAL*12 = 36000;

SELECT * FROM EMP
WHERE SAL > 2000;

SELECT * FROM EMP
WHERE ENAME >= 'F';

SELECT * FROM EMP
WHERE ENAME >= 'FORZ';

SELECT * FROM EMP
WHERE NOT SAL = 3000;

SELECT * FROM EMP
WHERE JOB = 'MANAGER'
	OR JOB = 'SALESMAN'
	OR JOB = 'CLERK';

SELECT * FROM EMP
WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT * FROM EMP
WHERE JOB != 'MANAGER'
	OR JOB <> 'SALESMAN'
	OR JOB ^= 'CLERK';

SELECT * FROM EMP
WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT * FROM EMP
WHERE SAL >= 2000
AND SAL <= 3000;

SELECT * FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE ENAME LIKE 'S%';

SELECT * FROM EMP
WHERE ENAME LIKE '_L%';

SELECT * FROM EMP
WHERE ENAME LIKE '%AM%';

SELECT * FROM EMP
WHERE ENAME NOT LIKE '%AM%';

SELECT * FROM EMP
WHERE COMM = NULL;

SELECT * FROM EMP
WHERE COMM IS NULL; -- NULL인지 체크

SELECT * FROM EMP
WHERE COMM IS NULL;

SELECT * FROM EMP
WHERE MGR IS NOT NULL; -- MGR != NULL 이라고 하면 의미가 다름



