CREATE TABLE DEPT_TCL
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

SELECT * FROM DEPT_TCL;

ROLLBACK;

COMMIT;

DELETE FROM DEPT_TCL;

CREATE TABLE EMP_DDL(
EMPNO	NUMBER(4),
ENAME	VARCHAR2(10),
JOB		VARCHAR2(9),
MGR 	NUMBER(4),
HIREDATE DATE,
SAL		NUMBER(7,2),
COMM		NUMBER(7,2),
DEPTNO		NUMBER(2)
);

SELECT * FROM EMP_DDL;

CREATE TABLE EMP_DDL_30
AS SELECT * FROM EMP
WHERE DEPTNO = 30;

SELECT * FROM EMP_DDL_30;

SELECT * FROM HR.EMPLOYEES;

-- 테이블명 MEMBER (userid, password, email)
-- HR.EMAIL --> USERID				SKING
-- PASSWORD 컬럼은 USERID와 동일한 값	SKING
-- EMAIL 컬럼	기존 EMAIL @galapagos.org 	sking@galapagos.org
-- 문자열 결합 : ||

CREATE TABLE MEMBER
AS
	SELECT EMAIL userid, EMAIL password, LOWER(EMAIL) || '@galapagos.org' email
	FROM HR.EMPLOYEES;

SELECT * FROM MEMBER;

-- update 문 사용하여 userid와 password를 소문자로 변경
UPDATE MEMBER
SET PASSWORD = LOWER(PASSWORD),
	USERID = LOWER(USERID);
	
CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

COMMIT;

ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

RENAME EMP_ALTER TO EMP_RENAME;

SELECT * FROM EMP_RENAME;

TRUNCATE TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;

DROP TABLE EMP_RENAME;

ROLLBACK;

SELECT ROWID, E.*
FROM EMP E;

CREATE TABLE TABLE_NOTNULL(
LOGIN_ID VARCHAR(20) NOT NULL,
LOGIN_PWD VARCHAR(20) NOT NULL,
TEL VARCHAR2(20)
);

SELECT * FROM TABLE_NOTNULL;

-- LOGIN_PWD는 NOT NULL 이라서 에러
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', NULL, '010-1234-1413'); 

-- TEL은 NULL이 되므로 에러 없음
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD)
VALUES('TEST_ID_01', '010-1234-1413'); 

-- 에러
UPDATE TABLE_NOTNULL
SET LOGIN_PWD = NULL
WHERE LOGIN_ID = 'TEST_ID_01';

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS;

CREATE TABLE TABLE_NOTNULL2(
	LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
	LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
	TEL VARCHAR2(20)
);

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL2';

-- 이미 NULL 값이 있다면 변경 실패
ALTER TABLE TABLE_NOTNULL 
MODIFY(TEL NOT NULL);


UPDATE TABLE_NOTNULL
SET TEL = '010-1234-5678'
WHERE LOGIN_ID = 'TEST_ID_01';

SELECT * FROM TABLE_NOTNULL;

ALTER TABLE TABLE_NOTNULL2
MODIFY(TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);

SELECT * FROM TABLE_NOTNULL2;

ALTER TABLE TABLE_NOTNULL2
RENAME CONSTRAINT TBLNN_TEL_NN TO TBLNN2_TEL_NN;

ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT TBLNN2_TEL_NN;

DROP TABLE TABLE_UNIQUE;
CREATE TABLE TABLE_UNIQUE(
	LOGIN_ID VARCHAR2(20) CONSTRAINTS TBLUNQ2_LGNID_UNQ UNIQUE,
	LOGIN_PWD VARCHAR2(20) CONSTRAINTS TBLUNQ2_LGNPW_NN NOT NULL,
	TEL VARCHAR2(20)
);

SELECT * FROM TABLE_UNIQUE;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');

-- UNIQUE 제약 조건으로 인한 중복 에러
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_02', 'PWD01', '010-1234-5678');

-- NULL은 중복 허용. 값이 없는 것이라서.
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD01', '010-1234-5678');

DROP TABLE TABLE_PK;
CREATE TABLE TABLE_PK(
	LOGIN_ID VARCHAR2(20) CONSTRAINTS TBPK_LGNID_PK PRIMARY KEY,
	LOGIN_PWD VARCHAR2(20) CONSTRAINTS TBPK_LGNPW_NN NOT NULL,
	TEL VARCHAR2(20)
);
SELECT * FROM TABLE_PK;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_PK';

INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');

-- PRIMARY KEY 제약 조건으로 인한 중복 에러
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD02', '010-2234-5678');

-- PRIMARY KEY 제약 조건으로 NULL값 불가능 에러
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD02', '010-2234-5678');

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME,
	R_OWNER, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP','DEPT');

-- 50이라는 포린키가 없어서 에러
INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(9999, '홍길동', 'CLERK', '7788', TO_DATE('2017/04/30', 'YYYY/MM/DD'),
1200, NULL, 50);

-- 컬럼 레벨에서 PK 선언
DROP TABLE DEPT_FK;
CREATE TABLE DEPT_FK(
	DEPTNO NUMBER(2) CONSTRAINTS DEPTFK_DEPTNO_PK PRIMARY KEY,
	DNAME VARCHAR2(14),
	LOC VARCHAR2(13)
);
SELECT * FROM DEPT_FK;

-- 테이블 레벨에서 PK 선언
DROP TABLE DEPT_FK;
CREATE TABLE DEPT_FK(
	DEPTNO NUMBER(2),
	DNAME VARCHAR2(14),
	LOC VARCHAR2(13),
	CONSTRAINTS DEPTFK_DEPTNO_PK PRIMARY KEY(DEPTNO)
);
SELECT * FROM DEPT_FK;

-- 자식 테이블, 컬럼 레벨에서 PK, FK 선언
DROP TABLE EMP_FK;
CREATE TABLE EMP_FK(
	EMPNO NUMBER(4) CONSTRAINTS EMPFK_DEPTNO_PK PRIMARY KEY,
	ENAME VARCHAR2(10),
	JOB VARCHAR2(9),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7, 2),
	COMM NUMBER(7, 2),
	DEPTNO NUMBER(2) CONSTRAINTS EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
);
SELECT * FROM EMP_FK;

-- 자식 테이블, 테이블 레벨에서 PK, FK 선언
DROP TABLE EMP_FK;
CREATE TABLE EMP_FK(
	EMPNO NUMBER(4),
	ENAME VARCHAR2(10),
	JOB VARCHAR2(9),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7, 2),
	COMM NUMBER(7, 2),
	DEPTNO NUMBER(2),
	CONSTRAINTS EMPFK_DEPTNO_PK PRIMARY KEY(EMPNO),
	CONSTRAINTS EMPFK_DEPTNO_FK FOREIGN KEY(DEPTNO)
		REFERENCES DEPT_FK(DEPTNO) ON DELETE SET NULL --DEPT_FK의 행을 삭제 시,
		-- EMP_FK에서 해당 행을 참조하고 있다면 NULL로 대체
);
SELECT * FROM EMP_FK;

-- PARENT
INSERT INTO DEPT_FK
VALUES(10, 'TEST_NAME', 'TEST_LOC');

--CHILD
INSERT INTO EMP_FK
VALUES(9999, '홍길동', 'CLERK', NULL, TO_DATE('2017/04/30', 'YYYY/MM/DD'),
3000, NULL, 10);

--DEPT_FK의 행을 삭제 시, EMP_FK에서 해당 행을 참조하고 있다면 삭제 실패
DELETE FROM DEPT_FK
WHERE DEPTNO = 10;





